# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT
version: 2.1
jobs:
  build:
    docker:
        - image: circleci/golang:1.12.10-buster-node
        - image: circleci/postgres:9.5
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ledger_test

    working_directory: /go/src/github.com/communitybridge/ledger/
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            make setup_dev
      - run:
          name: Build Swagger
          command: |
            make swagger
      - run:
          name: Validate Swagger
          command: |
            make validate
      - run:
          name: Build
          command: |
            make build
      - run:
          name: Test
          command: |
            make test
      - run:
          name: Lint
          command: |
            make lint
    environment:
      DATABASE_HOST: "localhost"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_NAME: "ledger_test"
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/ledger_test?sslmode=disable"
      DB_MAX_CONNECTIONS: 2
      PORT: 8080