# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1-stretch-node
    working_directory: /go/src/github.com/communitybridge/ledger/
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            make setup_dev
      - run:
          name: Build Swagger
          command: |
            make swagger
      - run:
          name: Validate Swagger
          command: |
            make swagger-validate
      - run:
          name: Build
          command: |
            make build
      - run:
          name: Test
          command: |
            make test
      - run:
          name: Lint
          command: |
            cd cla-backend-go
            make lint